version: "3.3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: statistico
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statistico_odds_warehouse
    volumes:
      - .:/opt
    ports:
      - 5433:5432

  console: &console
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    volumes:
      - .:/opt
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_NAME: statistico_odds_warehouse
      DB_PASSWORD: password
      DB_USER: statistico
      DB_PORT: 5432
      QUEUE_DRIVER: log
    tty: true
    links:
      - postgres

  migrate:
    <<: *console
    command: [ "./bin/migrate" ]

  test:
    build:
      dockerfile: ./.docker/test/Dockerfile
      context: .
    volumes:
      - .:/opt
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_PASSWORD: password
      DB_NAME: statistico_odds_warehouse
      DB_USER: statistico
      DB_PORT: 5432
      QUEUE_DRIVER: log
    links:
      - postgres
    depends_on:
      - postgres

