version: "3.3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: statistico
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statistico_odds_warehouse
    volumes:
      - .:/opt
    ports:
      - 5433:5432
    networks:
      - statistico-odds-warehouse_default

  console: &console
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_NAME: statistico_odds_warehouse
      DB_PASSWORD: password
      DB_USER: statistico
      DB_PORT: 5432
    networks:
      - statistico_internal
      - statistico-odds-warehouse_default
    tty: true
    links:
      - postgres

  migrate:
    <<: *console
    command: ["make", "migrate"]

  statistico-odds-warehouse-grpc:
    <<: *console
    ports:
      - "50052:50051"
    networks:
      - statistico_internal
      - statistico-odds-warehouse_default
    command: [ "./grpc", "--port 50051" ]

  test:
    build:
      dockerfile: ./.docker/test/Dockerfile
      context: .
    volumes:
      - .:/opt
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_PASSWORD: password
      DB_NAME: statistico_odds_warehouse
      DB_USER: statistico
      DB_PORT: 5432
    links:
      - postgres
      - migrate
    depends_on:
      - postgres
      - migrate
    networks:
      - statistico-odds-warehouse_default

networks:
  statistico-odds-warehouse_default:
    external: false
  statistico_internal:
    external: true
