version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
  aws-ecs: circleci/aws-ecs@3.1.0

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - release-images:
          context: aws
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - deploy-to-production:
          context: aws
          requires:
            - build-and-test
            - release-images
          filters:
            branches:
              only: master

jobs:
  build-and-test:
    working_directory: ~/go/src/github.com/statistico/statistico-odds-warehouse
    machine: true
    environment:
      GOPATH: /home/circleci/go
    steps:
      - checkout
      - run:
          name: Build Release Image
          command: |
            docker network create statistico_internal
            docker-compose -f docker-compose.build.yml up -d --build
      - run:
          name: Test Release Image
          command: |
            docker-compose -f docker-compose.build.yml run test gotestsum -f short-verbose
      - run:
          name: Cache Built Images
          command: |
            chmod +x ./.circleci/deploy/docker-save.sh && ./.circleci/deploy/docker-save.sh
      - run:
          name: Build / Store Lambda
          command: |
            chmod +x ./.circleci/deploy/build-store.sh && ./.circleci/deploy/build-store.sh
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - docker-cache
            - artifacts

  release-images:
    executor: aws-cli/default
    steps:
      - checkout
      - *attach_workspace
      - setup_remote_docker
      - aws-cli/setup
      - run:
          name: Push images to ECR
          command: |
            chmod +x ./.circleci/deploy/docker-load.sh && ./.circleci/deploy/docker-load.sh
            chmod +x ./.circleci/deploy/docker-push.sh && ./.circleci/deploy/docker-push.sh

  deploy-to-production:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - aws-cli/setup
      - *attach_workspace
      - aws-ecs/update-service:
          family: 'statistico-odds-warehouse'
          cluster: 'statistico-grpc-services'
          container-image-name-updates: >
            container=statistico-odds-warehouse-grpc,tag=latest,
            container=statistico-odds-warehouse-migrate,tag=latest,
      - run:
          name: Deploy Artifacts to S3
          command: aws s3 sync --exclude="*" --include="*.zip" /tmp/workspace/artifacts/ s3://statistico-lambda
      - run:
          name: Update Lambda Function
          command: aws lambda update-function-code --function-name statistico-odds-warehouse --s3-bucket statistico-lambda --s3-key statistico-odds-warehouse.zip
