AWSTemplateFormatVersion: 2010-09-09
Description: EC2 related services for the statistico-odds-warehouse application.
Parameters:
  ServiceName:
    Type: String
    Default: statistico-odds-warehouse
  EnvironmentName:
    Type: String
    Default: statistico-production
  GroupName:
    Type: String
    Default: statistic-odds-warehouse-ecs-security-group
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref GroupName
      GroupDescription: Security group for the statistico-odds-warehouse ecs services
      VpcId:
        Fn::ImportValue: !Sub ${EnvironmentName}:VpcId
      Tags:
        - Key: Name
          Value: !Ref GroupName

  OutboundRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !GetAtt SecurityGroup.GroupId
      IpProtocol: -1
      CidrIp: 0.0.0.0/0

Outputs:
  SecurityGroupId:
    Description: ARN for the security group provisioned in this stack.
    Value: !GetAtt SecurityGroup.GroupId
    Export:
      Name: !Sub ${ServiceName}:SecurityGroupId
